### ISSUE TITLE
Attempted install leads to "Error: ENOENT: no such file or directory, open"

### ISSUE THREAD

**Issue by bunnybooboo** [defunkt/Zen#111]
I've just installed several other packages in an attempt to use Atom as a blogging tool. They installed fine. Zen keeps on hitting this error.

From the console:
```
Installing package Zen failed Error: Installing “Zen@0.18.0” failed.
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:533:21
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12) (node:13181) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

 fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/REDACTED/.atom/packages/Zen/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at Proxy.fs.readFileSync (fs.js:568:33)
    at Proxy.fs.readFileSync (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:476:42
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

(anonymous) @ /usr/lib/atom/node_modules/settings-view/lib/package-card.js:818
```
I'm using Arch Linux. I've tried reinstalling both Atom and APM via Pacman package manager. Deleting `.atom/storage/application.json`. All to no avail. :cry:

**Comment by mathieulagrange** [comment]
Same thing under mac os

**Comment by jest** [comment]
Same here, Ubuntu 16.04, Atom 1.23.1. What is interesting, `apm install zen` (lower-case package name) works. Same as `apm install defukt/Zen`.

Looks like problem with Atom itself: https://github.com/atom/settings-view/issues/1018

**Comment by bunnybooboo** [comment]
Thanks @jest - nice solve and I appreciate the link. That indeed resolves it until that fix gets merged upstream.
