### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by HenrikEckermann** [defunkt/Zen#113]
When I try to install Zen with `apm install Zen`in terminal on my mac, I get:

```
Installing Zen to /Users/myname/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/myname/.atom/packages/Zen/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by jest** [comment]
Same here, Ubuntu 16.04, Atom 1.23.1. What is interesting, `apm install zen` (lower-case package name) works. Same as `apm install defukt/Zen`.

Looks like problem with Atom itself: https://github.com/atom/settings-view/issues/1018

**Comment by Mustmus** [comment]
Aa
