### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDefaultCharWidth' of undefined

### ISSUE THREAD

**Issue by agargiulo** [defunkt/Zen#39]
[Enter steps to reproduce below:]

1. Install Zen
2. use default shortcut, `cmd-ctrl-z` to launch zen mode, crash happens

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: [Zen](https://github.com/defunkt/zen) package, v0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getDefaultCharWidth' of undefined

```
At /Users/agargiulo/.atom/packages/Zen/lib/zen.coffee:24

TypeError: Cannot read property 'getDefaultCharWidth' of undefined
  at Object.module.exports.toggle (/Users/agargiulo/.atom/packages/Zen/lib/zen.coffee:24:23)
  at atom-workspace.<anonymous> (/Users/agargiulo/.atom/packages/Zen/lib/zen.coffee:13:50)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:43.9 snippets:expand (input.hidden-input)
     -0:43.9 editor:indent (input.hidden-input)
     -0:43.7 snippets:next-tab-stop (input.hidden-input)
     -0:43.7 snippets:expand (input.hidden-input)
     -0:43.7 editor:indent (input.hidden-input)
     -0:43.6 snippets:next-tab-stop (input.hidden-input)
     -0:43.6 snippets:expand (input.hidden-input)
     -0:43.6 editor:indent (input.hidden-input)
  7x -0:43.4 core:backspace (input.hidden-input)
     -0:39.4 core:save (input.hidden-input)
     -0:37.5 core:move-down (input.hidden-input)
     -0:37.1 core:backspace (input.hidden-input)
     -0:36.3 core:save (input.hidden-input)
     -0:35.1 core:move-down (input.hidden-input)
     -0:34.7 core:backspace (input.hidden-input)
     -0:00.0 zen:toggle (div.settings-view.pane-item)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "jellybeans-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
jellybeans-syntax, v0.3.0
project-colorize, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by braver** [comment]
This is now handled by throwing a message if you're not in an editor view. It's not the cleanest, but we need to get a character width from an editor to be able to toggle the mode.

**Comment by agargiulo** [comment]
That's still better than it was, thanks for the update.
