### ISSUE TITLE
Specs passing?

### ISSUE THREAD

**Issue by miketheman** [defunkt/Zen#5]
I'm new to the whole Atom packages, so forgive me if this is totally BS.

I installed Zen package, and then ran "View" => "Developer" => "Run Atom Specs".

This produced:
```console
Error: Cannot find module '../lib/zen-view'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:279:25)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Object.<anonymous> (/Users/miketheman/.atom/packages/Zen/spec/zen-view-spec.coffee:1:11)
  at Object.<anonymous> (/Users/miketheman/.atom/packages/Zen/spec/zen-view-spec.coffee:1:1)
  at Module._compile (module.js:455:26)
...
```

So I went over to [this line][1] and replaced `lib/zen-view` to `lib/zen` - after which running the specs again produces failures:

```console
Zen
when the zen:toggle event is triggered
it attaches and then detaches the view
ReferenceError: WorkspaceView is not defined
ReferenceError: WorkspaceView is not defined
at zen-spec.coffee:12:26
TypeError: Cannot call method 'find' of undefined
TypeError: Cannot call method 'find' of undefined
at zen-spec.coffee:17:33
ZenView
it has one valid test
Expected 'life' to be 'easy'.
at zen-view-spec.coffee:6:20
```
So I'm not entirely certain "where" to start poking around looking to fix this.

In general, my Atom hangs and crashes frequently, which is why I'm wondering if it's in packages-world or core (there's no way to debug atom itself yet, is there?).

Anyways, thanks for listening!

[1]: https://github.com/defunkt/zen/blob/master/spec/zen-view-spec.coffee#L1

**Comment by braver** [comment]
This has been resolved in #6. Current rewrite in progress at #49 is so extensive new specs need to be created if we're going to have specs at all. In any case, this one can be closed.
