### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setSoftWrapped' of undefined

### ISSUE THREAD

**Issue by uliska** [defunkt/Zen#68]
[Enter steps to reproduce below:]

1. Have a document open in Zen mode
2. `Edit->Preferences`
3. Hit [shift]+F11 in order to exit the settings editor  
   (as it seems impossible to close it otherwise, there's no close "X" popping up in that constellation)

**Atom Version**: 1.0.0
**System**: LMDE 2
**Thrown From**: [Zen](https://github.com/defunkt/zen) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setSoftWrapped' of undefined

```
At /home/uliska/.atom/packages/Zen/lib/zen.coffee:111

TypeError: Cannot read property 'setSoftWrapped' of undefined
  at Object.module.exports.toggle (/home/uliska/.atom/packages/Zen/lib/zen.coffee:111:15)
  at atom-workspace.<anonymous> (/home/uliska/.atom/packages/Zen/lib/zen.coffee:28:59)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -4:43.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:40.6.0 editor:newline (atom-text-editor.editor.is-focused)
 13x -4:29.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:40.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:21.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:20.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -3:20.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:15.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -2:08.0 core:move-right (atom-text-editor.editor.is-focused)
 16x -2:07.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:46.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:46.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:45 core:move-left (atom-text-editor.editor.is-focused)
     -1:44.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.7.0 zen:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {},
  "Zen": {}
}
```

### Installed Packages

```coffee
# User
Zen, v0.14.0
language-latex, v0.6.1
latexer, v0.2.3
soft-wrap-indicator, v0.7.0
texlicious, v0.4.4
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by rm-code** [comment]
Strangely I can't reproduce it on OSX. 

I'm not the maintainer of this package, but I think [this](https://github.com/rm-code/Zen/commit/67d47b1f38f11d1cf29f21c13b59e04cc487c14d) might fix your issue. https://github.com/rm-code/Zen/tree/Fix_%2368

> (as it seems impossible to close it otherwise, there's no close "X" popping up in that constellation)

You should be able to close the tab via key shortcuts.

**Comment by rm-code** [comment]
Opened a pull request and updated the commit message.

**Comment by braver** [comment]
No repro here either although the PR makes sense. @uliska could you try if that fix solves your problem?

**Comment by rm-code** [comment]
@braver Check @uliska's comment [here](https://github.com/rm-code/Zen/commit/67d47b1f38f11d1cf29f21c13b59e04cc487c14d#comments)

**Comment by uliska** [comment]
Just what I wanted to say ;-)

**Comment by braver** [comment]
Alright, got it :) :+1:
