### ISSUE TITLE
Failed to activate the Zen package

### ISSUE THREAD

**Issue by dealonzo** [defunkt/Zen#85]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [Zen](https://github.com/defunkt/zen) package, v0.16.3

### Stack Trace

Failed to activate the Zen package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/user/.atom/packages/Zen/lib/zen.coffee:3:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:740:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:48.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:01.1.0 zen:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/user/Atom Projects/github"
  }
}
```

### Installed Packages

```coffee
# User
Zen, v0.16.3

# Dev
No dev packages
```

**Comment by rm-code** [comment]
I can't reproduce it on my macbook. Does it only happen in certain situations? Can you please describe what you do before it throws the error?

**Comment by julio8a** [comment]
@rm-code I literally just finished installing the app, I got error message at first launch.

**Comment by julio8a** [comment]
@rm-code I literally just finished installing the app, I got error message at first launch.

Stack tree:
```
Failed to activate the Zen package
Cannot read property 'command' of undefined
Hide Stack Trace
TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/julio/.atom/packages/Zen/lib/zen.coffee:3:23)
    at Package.module.exports.Package.activateNow (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/julio/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
The error was thrown from the Zen package. This issue has already been reported.
```

**Comment by JGarrido** [comment]
Just opened Atom after a good 6 months or so of non-use, updated some packages it notified me were at of date, then updated Atom itself, and received this message after restart. Closed/reopened, and I still get it.

**Comment by braver** [comment]
> Upgraded from 0.6.0 to current, and it seems to be resolved now.
